In [5]:
import pandas as pd
import numpy as np


In [6]:
iris = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'label'])


In [8]:
x = iris.drop(['label'],axis=1)
y =iris['label']
x.head()            


sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

# Removing feature with low variance

In [14]:
from sklearn.feature_selection import VarianceThreshold
sel= VarianceThreshold(threshold=0.5)
x_vt=sel.fit_transform(x)
x_vt[:5] #here sepal width got removed

array([[5.1, 1.4, 0.2],
       [4.9, 1.4, 0.2],
       [4.7, 1.3, 0.2],
       [4.6, 1.5, 0.2],
       [5. , 1.4, 0.2]])

# Univariate  feature selection

In [17]:
from sklearn.feature_selection import SelectKBest, SelectPercentile, chi2

X_sb = SelectKBest(chi2, k=2).fit_transform(x, y) # chi2: used score k: number of features to select
print(X_sb.shape)
X_sb[:5]

(150, 2)


array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2]])

In [18]:
X_sp = SelectPercentile(chi2, percentile=50).fit_transform(x,y)
print(X_sp.shape)
X_sp[:5]

(150, 2)


array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2]])

In [20]:
X_sp = SelectPercentile(chi2, percentile=75).fit_transform(x, y)
print(X_sp.shape)
X_sp[:5]

(150, 3)


array([[5.1, 1.4, 0.2],
       [4.9, 1.4, 0.2],
       [4.7, 1.3, 0.2],
       [4.6, 1.5, 0.2],
       [5. , 1.4, 0.2]])

# Feature Selection using selectFromModel

In [26]:
from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel

clf = LinearSVC(C=0.01, penalty="l1", dual=False) # We chose C smaller then default so fewer features were selected
clf.fit(x, y)

model = SelectFromModel(clf, prefit=True)
X_sfm = model.transform(x)

print(X_sfm.shape)
X_sfm[:5]

(150, 3)


/home/mamata/day_one_task/venv/lib/python3.6/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


array([[5.1, 3.5, 1.4],
       [4.9, 3. , 1.4],
       [4.7, 3.2, 1.3],
       [4.6, 3.1, 1.5],
       [5. , 3.6, 1.4]])