In [6]:
import numpy as np

In [7]:
mul_arr1 = np.arange(1,17).reshape(4,4)
mul_arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [8]:
mul_arr2 = np.arange(17,33).reshape(4,4)
mul_arr2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [20]:
#concatination horizontally ie increase rows
np.concatenate((mul_arr1,mul_arr2))
# np.vstack((mul_arr1,mul_arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [22]:
#concatination vertically  ie increase columns
np.concatenate((mul_arr1,mul_arr2),axis=1)
# np.hstack((mul_arr1,mul_arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [24]:
np.hstack((mul_arr1,mul_arr2,mul_arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32, 29, 30, 31, 32]])

# SPLIT FUNCTION

In [27]:
#spliting mul_arr1 into two parts
mul_arr1
np.split(mul_arr1,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [28]:
type(np.split(mul_arr1,2))

list

In [29]:
list1 =np.split(mul_arr1,2)

In [30]:
list1

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [31]:
type(list1)

list

In [32]:
type(list1[0])

numpy.ndarray

In [33]:
#spliting mul_arr1 rowise
np.split(mul_arr1,2,axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [34]:
mul_arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [35]:
d1 = np.array([4,7,9,6,8])

In [36]:
d1.ndim

1

In [41]:
arr_split=np.split(d1,[1,3])

In [45]:
type(arr_split[2])

numpy.ndarray