In [1]:
import numpy as np

In [6]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# elementwise addition
arr3 = arr1 + arr2
print(arr3)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [11]:
#elementwise addition
np.add(arr1,arr3)

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [13]:
#elementwise substraction
np.subtract(arr1,arr3)

array([[-1, -2, -3],
       [-4, -5, -6],
       [-7, -8, -9]])

In [15]:
#elementwise division
# np.division(arr1,arr2)
# np.multiply(arr1,arr2)

In [17]:
#matrix product
max1 = np.arange(1,10).reshape(3,3)
max2 = np.arange(1,10).reshape(3,3)
max1.dot(max2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [24]:
#finding the maximumvalue in an arrar
arr_max= np.arange(1,23,3).reshape(2,4)
arr_max

array([[ 1,  4,  7, 10],
       [13, 16, 19, 22]])

In [26]:
arr_max.max()   #here 22 is the maximum value

22

In [28]:
#finding the index of the maximum element in the matrix
arr_max.argmax()

7

In [29]:
# finding the maximum value in each column or rows
# axis 0 represent colmns and axis1 represent rows
arr_max.max(axis=0) 

array([13, 16, 19, 22])

In [30]:
arr_max.max(axis=1) 

array([10, 22])

In [31]:
# finding the minimum value in each column or rows
arr_max.min(axis=0)

array([ 1,  4,  7, 10])

In [32]:
arr_max.min(axis=1)

array([ 1, 13])

In [33]:
#finding the index of the maximum element in the matrix
arr_max.argmin()

0

In [34]:
#get the total sum of an array
arr_max

array([[ 1,  4,  7, 10],
       [13, 16, 19, 22]])

In [35]:
np.sum(arr_max)

92

In [37]:
#getting the columnwise sum of the matrix
np.sum(arr_max,axis=0)

array([14, 20, 26, 32])

In [38]:
#calculating the average of the matrix
np.mean(arr_max)

11.5

In [39]:
#getting the square root of every element of a matrix
np.sqrt(arr_max)

array([[1.        , 2.        , 2.64575131, 3.16227766],
       [3.60555128, 4.        , 4.35889894, 4.69041576]])

In [40]:
#calculating standard deviation
np.std(arr_max)

6.87386354243376

In [41]:
#calculating the exponent of every element
np.exp(arr_max)

array([[2.71828183e+00, 5.45981500e+01, 1.09663316e+03, 2.20264658e+04],
       [4.42413392e+05, 8.88611052e+06, 1.78482301e+08, 3.58491285e+09]])

In [42]:
#calculating the natural log of every element
np.log(arr_max)

array([[0.        , 1.38629436, 1.94591015, 2.30258509],
       [2.56494936, 2.77258872, 2.94443898, 3.09104245]])

In [43]:
np.log10(arr_max)

array([[0.        , 0.60205999, 0.84509804, 1.        ],
       [1.11394335, 1.20411998, 1.2787536 , 1.34242268]])